INSERT INTO users (nik, name, email, password, role, gender, status, division_id, position_id, office_id, tanggal_aktif_kerja, must_change_password, created_at, updated_at)
VALUES
(
'AP002993002',
'SUTRISNO',
'AP002993002@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002995002',
'L.EKO YUNIATI NINGGALINGRUM',
'AP002995002@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'head teller'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002996001',
'YETI SULISTYORINI',
'AP002996001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP001997002',
'TRI HANDAYANI',
'AP001997002@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002998001',
'YUSTINUS YUNIANTO PURNOMO',
'AP002998001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002999001',
'APRILIANA AGUS HERDIANA',
'AP002999001@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004999002',
'DONO SUGITO',
'AP004999002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002017022',
'NANANG PRASETYO',
'AP002017022@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2017-07-04',
0,
NOW(),
NOW()
),
(
'AP002000002',
'SUWANTO',
'AP002000002@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003000003',
'THOMAS KUSDIANTO',
'AP003000003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003000004',
'TRI PUSPA ANDAYANIK',
'AP003000004@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'koordinator kredit'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002017001',
'NURHUDA ANDRI DARMAWAN',
'AP002017001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2017-03-09',
0,
NOW(),
NOW()
),
(
'AP004001004',
'HARI SURYANTO',
'AP004001004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002002002',
'ANIN NUR KOLIFAH',
'AP002002002@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'umum'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP001002003',
'AGUS NAWAWI',
'AP001002003@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie it'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002003001',
'VADIA ELIYA SANTI',
'AP002003001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004003002',
'YULI TRIANAWATI',
'AP004003002@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002003003',
'KHUSNUL ARIFIN',
'AP002003003@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002003004',
'PAULUS WIWIT UNTORO',
'AP002003004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'umum'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002004001',
'PETRUS HERIANTO',
'AP002004001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'umum'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003004002',
'NOFENTY',
'AP003004002@bprap.com',
'password123',
'kasie',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002005001',
'BAMBANG SOLIKIN',
'AP002005001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002005002',
'CHRISTIYAN DONY CAHYANTO',
'AP002005002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005017003',
'FRANSISKA SANJAYA',
'AP005017003@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2017-03-17',
0,
NOW(),
NOW()
),
(
'AP004005006',
'NANANG TRI WAHYUDI',
'AP004005006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002006002',
'ALIEFI ZUBAIDI PURNOMO',
'AP002006002@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003006003',
'NURCAHYONO',
'AP003006003@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005006005',
'ROSMALA SARI P',
'AP005006005@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005006006',
'JONI LESMANA',
'AP005006006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002006007',
'SAMSUL HUDA',
'AP002006007@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005008001',
'DYAH AYU ROSALIA',
'AP005008001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005008003',
'INDRIANI P',
'AP005008003@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003009002',
'MOH. FUAD HASYIM',
'AP003009002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004009003',
'CATUR SUPRAPTO',
'AP004009003@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004009006',
'TITIS LESTARI',
'AP004009006@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005009007',
'SURYANTO',
'AP005009007@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'umum'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006009008',
'LULUK SUHARIYAWATI',
'AP006009008@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003009010',
'ARRY CHANDRA ANDHIKA',
'AP003009010@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003009013',
'EKO SANTOSO',
'AP003009013@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002010001',
'JOHAN SAFI''I',
'AP002010001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002010003',
'YUSA DEWA SUGINDA',
'AP002010003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003012004',
'MUJIANTO',
'AP003012004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005010006',
'IIN FAUZIAH',
'AP005010006@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003010008',
'AGUS BUDI AJI',
'AP003010008@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002010013',
'IKASARI INDRAWATI',
'AP002010013@bprap.com',
'password123',
'kasie',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002010014',
'WIWIED INDAH PRATIWI',
'AP002010014@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala bagian kepatuhan & manrisk'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005017024',
'WIKY REZA RAHMAWATI',
'AP005017024@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2017-07-04',
0,
NOW(),
NOW()
),
(
'AP002010017',
'MAHAR FILHANI',
'AP002010017@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006011002',
'RENY SULISTYANI',
'AP006011002@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006011008',
'MOCHAMAD JEFRI SETYAWAN',
'AP006011008@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006011009',
'EKY ANANG RISTANTO',
'AP006011009@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003011010',
'CAHYO LUHUR BUONO',
'AP003011010@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003012001',
'DIDIK NURKHOLIS',
'AP003012001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003015001',
'YOYOK YUNI SAPUTRO',
'AP003015001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006012005',
'DIAN KARTIKA SARI',
'AP006012005@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006012006',
'MUCHAMAD ZUNAIDI',
'AP006012006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005012007',
'ICHWAN KHANAFI',
'AP005012007@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006012008',
'DALLAS APRIAWAN',
'AP006012008@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003023003',
'SITI MASFI''AH',
'AP003023003@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2017-07-12',
0,
NOW(),
NOW()
),
(
'AP003012011',
'SUHADAK AMIRUDIN',
'AP003012011@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003013001',
'EBIM SEPTIA AJI PRANATA',
'AP003013001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003013005',
'NUR WINDA SUSANTI',
'AP003013005@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005014007',
'MOH. ARIF ARDIANTO',
'AP005014007@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006014009',
'MUHAMMAD TEGUH FAUZAN',
'AP006014009@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005014013',
'ADI WALUYO',
'AP005014013@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006014014',
'JEFRI FERNANDES ARISMA',
'AP006014014@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005014017',
'ADETIYA',
'AP005014017@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002014018',
'YANDI SILVI NOVITA SARI',
'AP002014018@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003014004',
'MOHAMAD SUKRON KARUNIA',
'AP003014004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005015005',
'ROBY FAJAR SUKMANA',
'AP005015005@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003013009',
'SULISTYANINGSIH',
'AP003013009@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002015014',
'IVA GALIH AYU VANDINI',
'AP002015014@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff skai'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003015018',
'ELFIRA WIEN KARTIKA',
'AP003015018@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002015022',
'LAILATUL FITRIA AFIFAH',
'AP002015022@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006015025',
'LUKI ARDIYANSAH',
'AP006015025@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006017008',
'EMY DWI AYU NINGTIA',
'AP006017008@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2017-04-26',
0,
NOW(),
NOW()
),
(
'AP004015030',
'DANA FIRMANSAH',
'AP004015030@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005015032',
'CHRISTINA DWI SUSANTI',
'AP005015032@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004016001',
'HERU FINARTO',
'AP004016001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002016003',
'JEFFRI MARTHIN PANJI NUGROHO',
'AP002016003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff skai'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003016006',
'WILDAN BAYU BASTIAN',
'AP003016006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP001016007',
'SATRIADI PURWANTO',
'AP001016007@bprap.com',
'password123',
'hrd',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala bagian hrd'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP001016008',
'WINDHARU DHANY BINTORO',
'AP001016008@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'collection'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie collection'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP001016009',
'AGUS SETIAWAN',
'AP001016009@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004016011',
'RONI FAHRUROZI',
'AP004016011@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP002017012',
'SISCA BATERIA ANGGRAINI',
'AP002017012@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'sekretaris direksi'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2017-05-02',
0,
NOW(),
NOW()
),
(
'AP003016014',
'AHMAD KHOLIS',
'AP003016014@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'collection'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie collection'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005016017',
'DIDIK TRIYONO',
'AP005016017@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'collection'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003016023',
'MUJIANTO',
'AP003016023@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP003016024',
'ARVIAN FAJAR PAMBUDI',
'AP003016024@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'collection'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP005016026',
'Wiyos Tri Nugroho',
'AP005016026@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'collection'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP004017037',
'RAMA ARI ZONA',
'AP004017037@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2017-08-30',
0,
NOW(),
NOW()
),
(
'AP002011001',
'YUANA',
'AP002011001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'umum'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-06-23',
0,
NOW(),
NOW()
),
(
'AP006017039',
'FARIDATU FADLILAH',
'AP006017039@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2017-09-07',
0,
NOW(),
NOW()
),
(
'AP002016044',
'ASIK NATANAEL',
'AP002016044@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2016-08-08',
0,
NOW(),
NOW()
),
(
'AP001016045',
'ENI KARYAWATI',
'AP001016045@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala bagian operasional'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2016-08-18',
0,
NOW(),
NOW()
),
(
'AP002016052',
'NURLELY DEWINDA SARI',
'AP002016052@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2016-10-31',
0,
NOW(),
NOW()
),
(
'AP002017016',
'YUSUF ENGGA DIKDAWAN',
'AP002017016@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2017-06-02',
0,
NOW(),
NOW()
),
(
'AP003017041',
'PUSPANINGAYU KUSUMA DEWI',
'AP003017041@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2017-11-02',
0,
NOW(),
NOW()
),
(
'AP006018006',
'ARI INDRA PURNAMA PUTRA',
'AP006018006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2018-02-19',
0,
NOW(),
NOW()
),
(
'AP001018010',
'LIYAGUSTIN KUSHARDI YANTINI',
'AP001018010@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala bagian skai'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2018-04-02',
0,
NOW(),
NOW()
),
(
'AP011007002',
'ANNA PURBASARI',
'AP011007002@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011007003',
'FARIDA CHOIRUL NIKMAH',
'AP011007003@bprap.com',
'password123',
'kabag-pincab',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011006001',
'NIA RENGGAWATI',
'AP011006001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011013001',
'DHITA KRISTANTRI',
'AP011013001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011017001',
'GURIT TRI SANTOSO',
'AP011017001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011012001',
'KRISTIAN ADI PUTRA',
'AP011012001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011018001',
'SLAMET DAROINI',
'AP011018001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011006002',
'RIO DHARMA SAYOGA',
'AP011006002@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP011006003',
'YEKHA YUANDA',
'AP011006003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP009008001',
'AVID KRESNO SAPUTRO',
'AP009008001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP009009003',
'MOCHAMAD NURIL EFENDI',
'AP009009003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-04-09',
0,
NOW(),
NOW()
),
(
'AP009008002',
'FERRY KURNIAWAN',
'AP009008002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP009017001',
'MARIA ULFA',
'AP009017001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008997001',
'RENI IKA RATNA SRI K.',
'AP008997001@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008003001',
'SUSILOWATI',
'AP008003001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008006002',
'ANANG ISWORO',
'AP008006002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008006001',
'AGUNG DWI WIYONO',
'AP008006001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008008002',
'YHUSTIKA NUR ELVANDARI',
'AP008008002@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie operasional'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008009002',
'REKXY KUMALASARI',
'AP008009002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008008003',
'EVA WAHYUNINGTYAS',
'AP008008003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-10',
0,
NOW(),
NOW()
),
(
'AP008013002',
'DWI RAHAYU',
'AP008013002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-11',
0,
NOW(),
NOW()
),
(
'AP002018011',
'EVA MEILINA SARI',
'AP002018011@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff skai'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2018-04-16',
0,
NOW(),
NOW()
),
(
'AP010016002',
'ANDIK SUGIANTO',
'AP010016002@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008013003',
'IRWAN EFENDI',
'AP008013003@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008014001',
'RENI SANJAYA',
'AP008014001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008004001',
'KARTIONO',
'AP008004001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008009004',
'WIJI RIATI',
'AP008009004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008015002',
'ANDI PURWANTO',
'AP008015002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008013005',
'ADE KURNIAWAN',
'AP008013005@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008015003',
'DIMAS AGDE SENNA',
'AP008015003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008016001',
'YULI NUR HASANAH',
'AP008016001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP008017001',
'CHANDRA WISUDA',
'AP008017001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012008001',
'DIAN RURIN PARAMARTHA',
'AP012008001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012016001',
'MOKHAMAD SAIFUL ANWAR',
'AP012016001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012015001',
'ANDIYANI HARTININGSIH',
'AP012015001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012985001',
'SITI ROHANI',
'AP012985001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012008003',
'NINA DAMAYANTI',
'AP012008003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012015002',
'REDY SUBAGIYO',
'AP012015002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP012001001',
'ARIF NURHIDAYAT',
'AP012001001@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2018-04-18',
0,
NOW(),
NOW()
),
(
'AP006018012',
'AHMAD RIYANTO',
'AP006018012@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007999003',
'ERLIN SURYANI',
'AP007999003@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'general'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007997001',
'EMY TRIWATI',
'AP007997001@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007003002',
'UMI SA''ADAH',
'AP007003002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP009016001',
'AGUS MAKSUM',
'AP009016001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007006002',
'MOH. YASIN',
'AP007006002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007004001',
'HADI SUSANTO',
'AP007004001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007007001',
'DURIYAH',
'AP007007001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009010',
'RIMA YULI UTARI',
'AP007009010@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009012',
'NURUL HIDAYATUS S',
'AP007009012@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepala kantor kas'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009013',
'RINDRA ARIES A',
'AP007009013@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007011001',
'EKA WULANSARI',
'AP007011001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007012001',
'SUGIARTO',
'AP007012001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007012002',
'SUKMAWAN ZAKARIA',
'AP007012002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009002',
'RESTI JAYAMAHASIH',
'AP007009002@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007015001',
'ANGGI YOGA PRATAMA',
'AP007015001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009006',
'ANDREAS BUDI PURNOMO',
'AP007009006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007015003',
'BAYU SAPUTRA',
'AP007015003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007016002',
'YULIANA',
'AP007016002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007016003',
'WISNU SASONGKO',
'AP007016003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007017001',
'KHOTMUL QORIAH',
'AP007017001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009001',
'RIKE ELY SUSANTI',
'AP007009001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007007002',
'ZAINAL ABIDIN',
'AP007007002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007011002',
'NUNGKY HEKMAWATI',
'AP007011002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007011003',
'WIWIN ANJARWATI',
'AP007011003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007014001',
'ANDIK WINARNO',
'AP007014001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007010002',
'ABDUL AZIS ZAINAL ABIDIN',
'AP007010002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007012003',
'LUKMANTO',
'AP007012003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007014002',
'NUR FITRIYAH',
'AP007014002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009004',
'M. ARIF EFENDI',
'AP007009004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009008',
'DEWI LESTARI',
'AP007009008@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'kediri'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP007009009',
'AFUFUDIN',
'AP007009009@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010997001',
'BINTI RODIYAH',
'AP010997001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010997002',
'NISFUL LAILI S HANDAYANI',
'AP010997002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010999001',
'KANTI RAHAYU',
'AP010999001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010006001',
'DWI APRIYONO',
'AP010006001@bprap.com',
'password123',
'kasie',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'kasie marketing'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010007001',
'ANIS ROCHMAWATI',
'AP010007001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010007002',
'CHAMDAN WAHAB',
'AP010007002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010009002',
'INDRA DWI PUTRANTO',
'AP010009002@bprap.com',
'password123',
'kabag-pincab',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'pimpinan cabang'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010009003',
'SONI WIBOWO',
'AP010009003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010002002',
'ISMAWATI',
'AP010002002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010010001',
'DINA SULISTIANA',
'AP010010001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010010004',
'EVI MAFIDATUL ILMI',
'AP010010004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010010005',
'IKE RATNAWATI',
'AP010010005@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010011001',
'YADIK IRAWANTO',
'AP010011001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010011002',
'IKROM BASUKI',
'AP010011002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010012001',
'PURI KUMALASARI',
'AP010012001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010013001',
'ADI ARIYONO',
'AP010013001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010013002',
'TOMMY SANJAYA',
'AP010013002@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010013003',
'ROHMAT JARNI',
'AP010013003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010014001',
'MOCH. MUHSON',
'AP010014001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010015001',
'HERU PRASETYO',
'AP010015001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010015003',
'NANDA SHELY DEVITA',
'AP010015003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP010016001',
'YANUAR SASMIYANTO',
'AP010016001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-04-23',
0,
NOW(),
NOW()
),
(
'AP008018014',
'MUJIONO',
'AP008018014@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-05-04',
0,
NOW(),
NOW()
),
(
'AP004018016',
'MEILYNDA AYU ZENA PUTRI',
'AP004018016@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2018-05-18',
0,
NOW(),
NOW()
),
(
'AP006018020',
'SULISTYOWATI',
'AP006018020@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2018-05-30',
0,
NOW(),
NOW()
),
(
'AP008018022',
'INTAN MUSTIKA DEWI',
'AP008018022@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-06-04',
0,
NOW(),
NOW()
),
(
'AP009018029',
'RAHAYU MUKTI MAHANANI',
'AP009018029@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2018-08-01',
0,
NOW(),
NOW()
),
(
'AP002018033',
'DONNY KURNIAWAN',
'AP002018033@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2018-08-06',
0,
NOW(),
NOW()
),
(
'AP010018034',
'WINDA DWI LUKI ANGGRAINI',
'AP010018034@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2018-08-06',
0,
NOW(),
NOW()
),
(
'AP008018040',
'SUPRIATIN',
'AP008018040@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2018-10-09',
0,
NOW(),
NOW()
),
(
'AP012018041',
'DJAYENG SETIYONO',
'AP012018041@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2018-10-09',
0,
NOW(),
NOW()
),
(
'AP006023004',
'HARIADI AGUS SANTOSO',
'AP006023004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'jombang'),
'2018-10-15',
0,
NOW(),
NOW()
),
(
'AP011018044',
'RITA ASTRIANA',
'AP011018044@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2018-11-13',
0,
NOW(),
NOW()
),
(
'AP009019003',
'DEFITA FEBRIYANTI',
'AP009019003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2019-01-14',
0,
NOW(),
NOW()
),
(
'AP009019004',
'WAWAN HERU PRASETYO',
'AP009019004@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2019-01-31',
0,
NOW(),
NOW()
),
(
'AP012019006',
'EKKY AYU ANJARSASI',
'AP012019006@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2019-02-06',
0,
NOW(),
NOW()
),
(
'AP002019020',
'KOKO HADI PURNOMO',
'AP002019020@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-03-21',
0,
NOW(),
NOW()
),
(
'AP002019021',
'SUGENG PURWANTO',
'AP002019021@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-03-21',
0,
NOW(),
NOW()
),
(
'AP002019022',
'KHOIRUL ANAM',
'AP002019022@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-03-21',
0,
NOW(),
NOW()
),
(
'AP002019023',
'ZAINUL MUSTOFA',
'AP002019023@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-03-21',
0,
NOW(),
NOW()
),
(
'AP002019024',
'FERI BAGUS WINANTO',
'AP002019024@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-05-03',
0,
NOW(),
NOW()
),
(
'AP002019025',
'PITOYO',
'AP002019025@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-05-03',
0,
NOW(),
NOW()
),
(
'AP002019026',
'ROY DWI ERWANTO',
'AP002019026@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-05-03',
0,
NOW(),
NOW()
),
(
'AP002019028',
'MARSONO',
'AP002019028@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'security'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-05-03',
0,
NOW(),
NOW()
),
(
'AP004019011',
'WINDA GIANTIKA',
'AP004019011@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'admin kredit staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2019-06-21',
0,
NOW(),
NOW()
),
(
'AP009019013',
'DONNI LAILATUL MASRUROH',
'AP009019013@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'caruban'),
'2019-07-01',
0,
NOW(),
NOW()
),
(
'AP003019016',
'IRMA NURDIANA CAHYANING PUTRI',
'AP003019016@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2019-08-02',
0,
NOW(),
NOW()
),
(
'AP002019017',
'EKA SUSANTI',
'AP002019017@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2019-08-02',
0,
NOW(),
NOW()
),
(
'AP012019019',
'DEDHY NOVA HENDRAYU',
'AP012019019@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'tulungagung'),
'2019-08-02',
0,
NOW(),
NOW()
),
(
'AP002019030',
'WINARNO HANDOKO',
'AP002019030@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'office boy'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2019-11-06',
0,
NOW(),
NOW()
),
(
'AP002020036',
'ZURIKE RIANDARAJATI',
'AP002020036@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'tabungan deposito'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2020-10-12',
0,
NOW(),
NOW()
),
(
'AP002022001',
'KHARISMA AYU PRABANINGTYAS',
'AP002022001@bprap.com',
'password123',
'staff',
'P',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2022-01-03',
0,
NOW(),
NOW()
),
(
'AP002022003',
'FAIZ KHOIRULLOH',
'AP002022003@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2022-02-03',
0,
NOW(),
NOW()
),
(
'AP003022005',
'INDAH MAYA DAMAYANTI',
'AP003022005@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2022-03-28',
0,
NOW(),
NOW()
),
(
'AP007022007',
'GINANJAR WAHYU PRATAMA',
'AP007022007@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2022-06-13',
0,
NOW(),
NOW()
),
(
'AP002022008',
'FIDYAZTI TRIYAS MARSANELLA',
'AP002022008@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2022-07-04',
0,
NOW(),
NOW()
),
(
'AP001022009',
'RHADIMAS HARSETA BUANA',
'AP001022009@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff skai'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2022-07-21',
0,
NOW(),
NOW()
),
(
'AP002022014',
'YOLANDA NOVITASARI',
'AP002022014@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2022-11-21',
0,
NOW(),
NOW()
),
(
'AP010022015',
'MUKHAMAD ZAINUDIN',
'AP010022015@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2022-12-02',
0,
NOW(),
NOW()
),
(
'AP008022016',
'AHMAD SOLIKIN',
'AP008022016@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2022-12-26',
0,
NOW(),
NOW()
),
(
'AP004022017',
'MAURA INTAN DANTYARSA',
'AP004022017@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'accounting staff'),
(SELECT id FROM offices WHERE nama_kantor = 'sambi'),
'2022-12-26',
0,
NOW(),
NOW()
),
(
'AP002023001',
'ANITA OKTAVIANA HIDAYAT',
'AP002023001@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2023-01-26',
0,
NOW(),
NOW()
),
(
'AP003023009',
'EGA PUTRI ARIYANTI',
'AP003023009@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2023-09-29',
0,
NOW(),
NOW()
),
(
'AP001024010',
'CANDRA MAULANA ABUDIN',
'AP001024010@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'kepatuhan & manrisk staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2024-02-05',
0,
NOW(),
NOW()
),
(
'AP002024011',
'ADELIA DWI AFRIANTI AYU SAPUTRI',
'AP002024011@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2024-05-06',
0,
NOW(),
NOW()
),
(
'AP007024013',
'MOCH ZUHAL ILHAMI',
'AP007024013@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2024-05-13',
0,
NOW(),
NOW()
),
(
'AP003024014',
'DINA KUSUMA ARDANI',
'AP003024014@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'gurah'),
'2024-07-17',
0,
NOW(),
NOW()
),
(
'AP002024015',
'MUHAMMAD FATHUR ROHIM',
'AP002024015@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2024-08-01',
0,
NOW(),
NOW()
),
(
'AP010024016',
'ARDHIAN RAHMAN HAKIM',
'AP010024016@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'wates'),
'2024-09-02',
0,
NOW(),
NOW()
),
(
'AP011024017',
'CANTIKA FEBRIANA',
'AP011024017@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2024-09-02',
0,
NOW(),
NOW()
),
(
'AP007024018',
'FERI WIJIANTORO',
'AP007024018@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2024-12-02',
0,
NOW(),
NOW()
),
(
'AP007024019',
'MUHHAMAD QOYYUM KRIDHO UTOMO',
'AP007024019@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'warujayeng'),
'2024-12-02',
0,
NOW(),
NOW()
),
(
'AP002025021',
'NICODEMOS AJI PRATIKTA',
'AP002025021@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2025-04-15',
0,
NOW(),
NOW()
),
(
'AP011025022',
'FRAN LISTIANTO',
'AP011025022@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2025-05-16',
0,
NOW(),
NOW()
),
(
'AP002025023',
'RIDLOWAN EKA NUR CAHYA',
'AP002025023@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'staff it'),
(SELECT id FROM offices WHERE nama_kantor = 'pusat'),
'2025-07-01',
0,
NOW(),
NOW()
),
(
'AP002025024',
'IKA AYU NOVITA SARI',
'AP002025024@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2025-07-07',
0,
NOW(),
NOW()
),
(
'AP002025025',
'ARDY BAGUS PRASETYO',
'AP002025025@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'driver'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2025-08-01',
0,
NOW(),
NOW()
),
(
'AP011025026',
'NABILLA ELVA FEBRIANDI',
'AP011025026@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'blitar'),
'2025-08-26',
0,
NOW(),
NOW()
),
(
'AP008025027',
'ALFIAN HIMAWAN',
'AP008025027@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'marketing'),
(SELECT id FROM positions WHERE nama_jabatan = 'account officer staff'),
(SELECT id FROM offices WHERE nama_kantor = 'nganjuk'),
'2025-10-01',
0,
NOW(),
NOW()
),
(
'AP003025028',
'AJENG KURNIA RAHAYU',
'AP003025028@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'teller'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2025-11-04',
0,
NOW(),
NOW()
),
(
'AP002025029',
'ZAINURROHMANAL HAKIM',
'AP002025029@bprap.com',
'password123',
'staff',
'L',
'approved',
(SELECT id FROM divisions WHERE nama_divisi = 'operasional'),
(SELECT id FROM positions WHERE nama_jabatan = 'customer service'),
(SELECT id FROM offices WHERE nama_kantor = 'pare'),
'2025-11-04',
0,
NOW(),
NOW()
);