INSERT INTO positions (nama_jabatan, created_at, updated_at) VALUES
('account officer staff', NOW(), NOW()),
('accounting staff', NOW(), NOW()),
('admin kredit staff', NOW(), NOW()),
('customer service', NOW(), NOW()),
('driver', NOW(), NOW()),
('head teller', NOW(), NOW()),
('staff it', NOW(), NOW()),
('kasie collection', NOW(), NOW()),
('kasie customer service', NOW(), NOW()),
('kasie it', NOW(), NOW()),
('kasie marketing', NOW(), NOW()),
('kasie operasional', NOW(), NOW()),
('kepala bagian hrd', NOW(), NOW()),
('kepala bagian kepatuhan & manrisk', NOW(), NOW()),
('kepala bagian operasional', NOW(), NOW()),
('kepala bagian skai', NOW(), NOW()),
('kepala kantor kas', NOW(), NOW()),
('kepatuhan & manrisk staff', NOW(), NOW()),
('koordinator kredit', NOW(), NOW()),
('office boy', NOW(), NOW()),
('pimpinan cabang', NOW(), NOW()),
('security', NOW(), NOW()),
('sekretaris direksi', NOW(), NOW()),
('staff skai', NOW(), NOW()),
('tabungan deposito', NOW(), NOW()),
('teller', NOW(), NOW()),
('umum', NOW(), NOW()),
('direksi', NOW(), NOW());
